
["Blood System"]
	#血液量に関する設定
	#血液量85%の閾値
	#Range: 0.0 ~ 100.0
	blood_damage_threshold_85 = 85.0
	#血液量70%の閾値
	#Range: 0.0 ~ 100.0
	blood_damage_threshold_70 = 70.0
	#血液量65%の閾値
	#Range: 0.0 ~ 100.0
	blood_damage_threshold_65 = 65.0
	#血液量60%の閾値
	#Range: 0.0 ~ 100.0
	blood_damage_threshold_60 = 60.0
	#血液量85~70%時のダメージ
	#Range: 0.0 ~ 1000.0
	blood_damage_85_70 = 4.0
	#血液量70~65%時のダメージ
	#Range: 0.0 ~ 1000.0
	blood_damage_70_65 = 8.0
	#血液量65~60%時のダメージ
	#Range: 0.0 ~ 1000.0
	blood_damage_65_60 = 12.0
	#血液量60%未満時のダメージ
	#Range: 0.0 ~ 999999.0
	blood_damage_below_60 = 99999.0
	#血液量ダメージの間隔（tick）
	#Range: 1 ~ 12000
	blood_damage_interval = 100

["Bleeding System"]
	#出血システムに関する設定
	#0.1~2ダメージ時の出血発生確率
	#Range: 0.0 ~ 1.0
	bleeding_chance_low_damage = 0.1
	#0.1~2ダメージ時の出血速度増加量
	#Range: 0.0 ~ 100.0
	bleeding_speed_increase_low = 1.0
	#2~5ダメージ時の出血速度増加量
	#Range: 0.0 ~ 100.0
	bleeding_speed_increase_mid = 3.0
	#5~10ダメージ時の出血速度増加量
	#Range: 0.0 ~ 100.0
	bleeding_speed_increase_high = 6.0
	#10ダメージ以上時の出血速度増加量
	#Range: 0.0 ~ 100.0
	bleeding_speed_increase_extreme = 9.0
	#出血回復の基本レート
	#Range: 0.0 ~ 10.0
	bleeding_recovery_base_rate = 0.1
	#包帯エフェクトの出血回復倍率
	#Range: 0.0 ~ 100.0
	bleeding_recovery_bandage_multiplier = 1.0
	#血小板エフェクトの出血回復倍率
	#Range: 0.0 ~ 100.0
	bleeding_recovery_platelet_multiplier = 5.0

["Blood Recovery"]
	#血液回復に関する設定
	#自然回復時の血液回復率（%/秒）
	#Range: 0.0 ~ 10.0
	blood_natural_recovery_rate = 0.5
	#輸血時の血液回復率（%/秒）
	#Range: 0.0 ~ 10.0
	transfusion_recovery_rate = 1.0

["Cardiac System"]
	#心停止・蘇生システムに関する設定
	#心停止時の蘇生確率減少率（%/分）
	#Range: 0.0 ~ 100.0
	resuscitation_chance_decay_rate = 5.0
	#心停止から強制死亡までの時間（分）
	#Range: 1 ~ 120
	cardiac_arrest_death_time = 20
	#アドレナリン投与時の蘇生確率回復率（%/秒）
	#Range: 0.0 ~ 10.0
	adrenaline_resuscitation_recovery_rate = 0.5

[Defibrillator]
	#除細動器に関する設定
	#除細動器のクールダウン時間（秒）
	#Range: 1 ~ 3600
	defibrillator_cooldown = 30
	#除細動器の充電時間（秒）
	#Range: 1 ~ 60
	defibrillator_charge_time = 2
	#VF時の除細動器成功率倍率
	#Range: 0.1 ~ 10.0
	defibrillator_vf_success_multiplier = 2.0
	#除細動器失敗時の状態移行確率
	#Range: 0.0 ~ 1.0
	defibrillator_transition_chance = 0.4

["IV System"]
	#点滴システムに関する設定
	#点滴パック1個の持続時間（秒）
	#Range: 1 ~ 3600
	iv_pack_duration = 60
	#点滴の有効範囲（ブロック）
	#Range: 1.0 ~ 100.0
	iv_range = 10.0

["Bandage System"]
	#包帯システムに関する設定
	#自分への包帯使用時間（秒）
	#Range: 1 ~ 60
	bandage_self_use_duration = 6
	#他人への包帯使用時間（秒）
	#Range: 1 ~ 60
	bandage_other_use_duration = 4
	#包帯エフェクトの持続時間（秒）
	#Range: 1 ~ 3600
	bandage_effect_duration = 60
	#自分への包帯使用時のエフェクトレベル増加
	#Range: 1 ~ 10
	bandage_self_level_increase = 1
	#他人への包帯使用時のエフェクトレベル増加
	#Range: 1 ~ 10
	bandage_other_level_increase = 2
	#包帯エフェクトの最大レベル
	#Range: 1 ~ 20
	bandage_max_level = 6

